#!/usr/bin/env python3
"""Publish the docs catalog into the public wiki; --check detects stale output."""
import argparse
import json
from pathlib import Path
import re
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / 'docs/wiki/catalog.json'
OUTPUT = ROOT / 'liwiro/frontend/lib/user-manual.ts'


def build():
    entries = json.loads(CATALOG.read_text())
    slugs = [entry['slug'] for entry in entries]
    if len(slugs) != len(set(slugs)):
        raise ValueError('Duplicate wiki slug')
    paths = {(ROOT / entry['source']).resolve(): entry['slug'] for entry in entries}
    result = []
    for order, entry in enumerate(entries):
        source = ROOT / entry['source']
        content = source.read_text().strip()
        if not content.startswith('# '):
            raise ValueError(f'Missing title: {source}')
        for related in entry['related']:
            if related not in slugs:
                raise ValueError(f'Unknown related page: {related}')
        def link(match):
            label, target = match.groups()
            if re.match(r'\w+:', target) or target.startswith('/'):
                return match.group(0)
            file, _, anchor = target.partition('#')
            dest = (source.parent / unquote(file)).resolve() if file else source.resolve()
            if dest in paths:
                slug = paths[dest]
                # MarkdownDocument prefixes heading IDs with the page slug.
                return f'[{label}](/wiki/{slug}' + (f'#{slug}-{anchor}' if anchor else '') + ')'
            # Local source files outside the public catalog have no HTTP route.
            return f'{label} (`{target}`)'
        content = re.sub(r'(?<!!)\[([^\]]+)\]\(([^)]+)\)',link,content)
        result.append({k:v for k,v in entry.items() if k!='source'} | {'order':(order+1)*10,'content':content})
    header = '''// Generated by scripts/build_wiki.py from docs/wiki/catalog.json and Markdown sources.
// Edit the source documents, then regenerate; do not edit this file directly.
export type UserManualEntry = {
  slug: string; title: string; summary: string; category: string; audience: string;
  subsystem: string; order: number; gettingStarted?: boolean; related?: string[];
  tags: string[]; content: string;
}

export const userManual: UserManualEntry[] = '''
    return header + json.dumps(result,ensure_ascii=False,indent=2) + '\n'


if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    output=build()
    if args.check:
        if OUTPUT.read_text()!=output:
            raise SystemExit('Wiki is stale: run python scripts/build_wiki.py')
        print('Wiki sources, related pages, and generated content are in sync.')
    else:
        OUTPUT.write_text(output)
        print(f'Generated {OUTPUT.relative_to(ROOT)}')
