from __future__ import annotations

from typing import Any


def _links(*items: tuple[str, str]) -> list[dict[str, str]]:
    return [{"title": str(title).strip(), "href": str(href).strip()} for title, href in items if str(title).strip() and str(href).strip()]


def _capability(
    capability_id: str,
    *,
    title: str,
    summary: str,
    subsystem: str,
    surface_id: str,
    surface_path: str,
    action_family: str,
    execution_mode: str,
    stage_support: list[str],
    supports: dict[str, bool] | None = None,
    permissions: list[str] | None = None,
    risk_level: str = "low",
    artifact_kind: str = "",
    manual_links: list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    return {
        "capabilityId": capability_id,
        "title": title,
        "summary": summary,
        "subsystem": subsystem,
        "surfaceId": surface_id,
        "surfacePath": surface_path,
        "actionFamily": action_family,
        "executionMode": execution_mode,
        "stageSupport": list(stage_support),
        "supports": {
            "verse": bool((supports or {}).get("verse", True)),
            "cli": bool((supports or {}).get("cli", True)),
            "ui": bool((supports or {}).get("ui", True)),
        },
        "permissions": [str(item).strip() for item in list(permissions or []) if str(item).strip()],
        "riskLevel": str(risk_level or "low").strip().lower(),
        "artifactKind": str(artifact_kind or "").strip(),
        "manualLinks": [
            {"title": str(item.get("title") or "").strip(), "href": str(item.get("href") or "").strip()}
            for item in list(manual_links or [])
            if isinstance(item, dict) and str(item.get("title") or "").strip() and str(item.get("href") or "").strip()
        ],
    }


_PLATFORM_CAPABILITIES: list[dict[str, Any]] = [
    _capability(
        "platform.navigation.change-location",
        title="Change Platform Location",
        summary="Move the user to the correct Liwiro surface before the next staged action continues.",
        subsystem="platform",
        surface_id="platform",
        surface_path="/verse-ai",
        action_family="move",
        execution_mode="client",
        stage_support=["move"],
        supports={"verse": True, "cli": False, "ui": True},
        risk_level="low",
        manual_links=_links(("Platform Foundations", "/wiki/platform-foundations"), ("Verse Agents", "/wiki/verse-agents-reference")),
    ),
    _capability(
        "auth.setup.bootstrap",
        title="Bootstrap Platform Setup",
        summary="Complete first-run setup and provision the first Liwiro super admin.",
        subsystem="platform",
        surface_id="setup",
        surface_path="/setup",
        action_family="setup",
        execution_mode="page",
        stage_support=["move", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="medium",
        manual_links=_links(("Auth and Access", "/wiki/auth-and-access"), ("Platform Foundations", "/wiki/platform-foundations")),
    ),
    _capability(
        "auth.session.manage",
        title="Manage Liwiro Session",
        summary="Sign in, sign out, or inspect the active Liwiro platform session.",
        subsystem="auth",
        surface_id="login",
        surface_path="/login",
        action_family="session",
        execution_mode="server",
        stage_support=["inspect", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="low",
        manual_links=_links(("Auth and Access", "/wiki/auth-and-access"), ("VDB Runtime", "/wiki/vdb-runtime-reference")),
    ),
    _capability(
        "platform.settings.manage",
        title="Manage Platform Settings",
        summary="Inspect or update control-plane settings that shape Liwiro runtime behavior.",
        subsystem="platform",
        surface_id="settings",
        surface_path="/settings",
        action_family="configure",
        execution_mode="page",
        stage_support=["move", "inspect", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="medium",
        manual_links=_links(("Platform Foundations", "/wiki/platform-foundations"), ("Auth and Access", "/wiki/auth-and-access")),
    ),
    _capability(
        "platform.users.manage",
        title="Manage Platform Users",
        summary="List, create, update, or delete Liwiro platform users and access policy.",
        subsystem="platform",
        surface_id="settings",
        surface_path="/settings",
        action_family="manage",
        execution_mode="server",
        stage_support=["move", "inspect", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        permissions=["MANAGE_SERVICES"],
        risk_level="high",
        manual_links=_links(("Auth and Access", "/wiki/auth-and-access"), ("Platform Foundations", "/wiki/platform-foundations")),
    ),
    _capability(
        "services.catalog.inspect",
        title="Inspect Service Fleet",
        summary="List services, open a selected service, and inspect runtime metadata.",
        subsystem="services",
        surface_id="service-manager",
        surface_path="/services",
        action_family="inspect",
        execution_mode="page",
        stage_support=["move", "inspect"],
        supports={"verse": True, "cli": True, "ui": True},
        permissions=["VIEW_SERVICES"],
        risk_level="low",
        manual_links=_links(("LAPIS Service Lifecycle", "/wiki/lapis-service-lifecycle"), ("Platform Foundations", "/wiki/platform-foundations")),
    ),
    _capability(
        "service.builder.generate",
        title="Generate Service Draft",
        summary="Prepare, validate, and generate a LAPIS-backed service in the Service Builder.",
        subsystem="services",
        surface_id="service-builder",
        surface_path="/service-builder",
        action_family="generate",
        execution_mode="page",
        stage_support=["move", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="medium",
        artifact_kind="service-builder-lapis",
        manual_links=_links(("LAPIS Service Lifecycle", "/wiki/lapis-service-lifecycle"), ("LAPIS Reference", "/wiki/lapis-reference")),
    ),
    _capability(
        "service.manager.configure",
        title="Edit Service Configuration",
        summary="Open the service detail editor and update runtime-facing or manager-state configuration.",
        subsystem="services",
        surface_id="service-manager",
        surface_path="/services",
        action_family="configure",
        execution_mode="page",
        stage_support=["move", "inspect", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        permissions=["VIEW_SERVICES"],
        risk_level="medium",
        manual_links=_links(("LAPIS Service Lifecycle", "/wiki/lapis-service-lifecycle"), ("LAPIS Reference", "/wiki/lapis-reference")),
    ),
    _capability(
        "service.manager.start",
        title="Start Service",
        summary="Start or restart a generated service through the Service Manager lifecycle path.",
        subsystem="services",
        surface_id="service-manager",
        surface_path="/services",
        action_family="start",
        execution_mode="server",
        stage_support=["move", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        permissions=["MANAGE_SERVICES"],
        risk_level="medium",
        artifact_kind="service-manager-action",
        manual_links=_links(("LAPIS Service Lifecycle", "/wiki/lapis-service-lifecycle"), ("Platform Foundations", "/wiki/platform-foundations")),
    ),
    _capability(
        "service.manager.stop",
        title="Stop Service",
        summary="Stop a generated service through the Service Manager lifecycle path.",
        subsystem="services",
        surface_id="service-manager",
        surface_path="/services",
        action_family="stop",
        execution_mode="server",
        stage_support=["move", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        permissions=["MANAGE_SERVICES"],
        risk_level="medium",
        artifact_kind="service-manager-action",
        manual_links=_links(("LAPIS Service Lifecycle", "/wiki/lapis-service-lifecycle"), ("Platform Foundations", "/wiki/platform-foundations")),
    ),
    _capability(
        "service.manager.delete",
        title="Delete Service",
        summary="Delete a generated service and optionally remove its data workspace.",
        subsystem="services",
        surface_id="service-manager",
        surface_path="/services",
        action_family="delete",
        execution_mode="server",
        stage_support=["move", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        permissions=["MANAGE_SERVICES"],
        risk_level="destructive",
        artifact_kind="service-manager-action",
        manual_links=_links(("LAPIS Service Lifecycle", "/wiki/lapis-service-lifecycle"), ("Platform Foundations", "/wiki/platform-foundations")),
    ),
    _capability(
        "service.manager.auth-keys.download",
        title="Download Service Auth Keys",
        summary="Export auth-service signing material for a generated service.",
        subsystem="services",
        surface_id="service-manager",
        surface_path="/services",
        action_family="export",
        execution_mode="server",
        stage_support=["move", "inspect", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        permissions=["VIEW_SERVICES"],
        risk_level="high",
        manual_links=_links(("LAPIS Service Lifecycle", "/wiki/lapis-service-lifecycle"), ("Auth and Access", "/wiki/auth-and-access")),
    ),
    _capability(
        "vdb.session.manage",
        title="Manage VDB Portal Session",
        summary="Connect, inspect, or disconnect the backend-owned VDB portal session.",
        subsystem="vdb",
        surface_id="vdb-portal",
        surface_path="/vdb-portal",
        action_family="session",
        execution_mode="server",
        stage_support=["move", "inspect", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="medium",
        manual_links=_links(("VDB Runtime", "/wiki/vdb-runtime-reference"), ("Auth and Access", "/wiki/auth-and-access")),
    ),
    _capability(
        "vdb.query.run",
        title="Run VDB Query",
        summary="Prepare, load, and execute a VDB portal query payload.",
        subsystem="vdb",
        surface_id="vdb-portal",
        surface_path="/vdb-portal",
        action_family="query",
        execution_mode="page",
        stage_support=["move", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="medium",
        artifact_kind="vdb-query",
        manual_links=_links(("VDB Runtime", "/wiki/vdb-runtime-reference"), ("VQL Reference", "/wiki/vql-reference")),
    ),
    _capability(
        "vdb.export.run",
        title="Export VDB Data",
        summary="Run a VDB export operation through the portal-backed backend integration.",
        subsystem="vdb",
        surface_id="vdb-portal",
        surface_path="/vdb-portal",
        action_family="export",
        execution_mode="server",
        stage_support=["move", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="high",
        manual_links=_links(("VDB Runtime", "/wiki/vdb-runtime-reference"), ("VQL Reference", "/wiki/vql-reference")),
    ),
    _capability(
        "vdb.domains.manage",
        title="Manage VDB Domains",
        summary="Inspect or create VDB domains through the backend-owned portal integration.",
        subsystem="vdb",
        surface_id="vdb-portal",
        surface_path="/vdb-portal",
        action_family="manage",
        execution_mode="server",
        stage_support=["move", "inspect", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="medium",
        manual_links=_links(("VDB Runtime", "/wiki/vdb-runtime-reference"), ("Platform Foundations", "/wiki/platform-foundations")),
    ),
    _capability(
        "vdb.rbac.manage",
        title="Manage VDB RBAC",
        summary="Inspect or change VDB RBAC state through the portal-backed command layer.",
        subsystem="vdb",
        surface_id="vdb-portal",
        surface_path="/vdb-portal",
        action_family="rbac",
        execution_mode="server",
        stage_support=["move", "inspect", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="high",
        manual_links=_links(("VDB Runtime", "/wiki/vdb-runtime-reference"), ("Auth and Access", "/wiki/auth-and-access")),
    ),
    _capability(
        "vi.portal.configure",
        title="Configure VI Portal",
        summary="Inspect or update the VI portal connection and managed workspace settings.",
        subsystem="vi",
        surface_id="vi-portal",
        surface_path="/vi-portal",
        action_family="configure",
        execution_mode="page",
        stage_support=["move", "inspect", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="medium",
        manual_links=_links(("VI Portal Runtime", "/wiki/vi-portal-runtime"), ("Platform Foundations", "/wiki/platform-foundations")),
    ),
    _capability(
        "vi.files.manage",
        title="Manage VI Files",
        summary="Browse, read, create, update, move, or delete files in the VI portal workspace.",
        subsystem="vi",
        surface_id="vi-portal",
        surface_path="/vi-portal",
        action_family="manage",
        execution_mode="page",
        stage_support=["move", "inspect", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="medium",
        manual_links=_links(("VI Portal Runtime", "/wiki/vi-portal-runtime"), ("Versa Reference", "/wiki/versa-reference")),
    ),
    _capability(
        "vi.script.draft",
        title="Draft and Run Versa Script",
        summary="Prepare Versa source, load it into the VI editor, and run it in the VI terminal.",
        subsystem="vi",
        surface_id="vi-portal",
        surface_path="/vi-portal",
        action_family="run",
        execution_mode="page",
        stage_support=["move", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="low",
        artifact_kind="vi-script",
        manual_links=_links(("VI Portal Runtime", "/wiki/vi-portal-runtime"), ("Versa Reference", "/wiki/versa-reference")),
    ),
    _capability(
        "vi.terminal.manage",
        title="Manage VI Terminal Session",
        summary="Create, inspect, or stop the live VI terminal session.",
        subsystem="vi",
        surface_id="vi-portal",
        surface_path="/vi-portal",
        action_family="terminal",
        execution_mode="server",
        stage_support=["move", "inspect", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="low",
        manual_links=_links(("VI Portal Runtime", "/wiki/vi-portal-runtime"), ("Versa Reference", "/wiki/versa-reference")),
    ),
    _capability(
        "vi.repl.manage",
        title="Manage VI REPL Session",
        summary="Start, send input to, or stop the VI REPL session.",
        subsystem="vi",
        surface_id="vi-portal",
        surface_path="/vi-portal",
        action_family="repl",
        execution_mode="server",
        stage_support=["move", "inspect", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="low",
        manual_links=_links(("VI Portal Runtime", "/wiki/vi-portal-runtime"), ("Versa Reference", "/wiki/versa-reference")),
    ),
    _capability(
        "vi.modules.manage",
        title="Manage VI Modules",
        summary="Inspect, create, update, delete, and assign VI modules.",
        subsystem="vi",
        surface_id="vi-portal",
        surface_path="/vi-portal",
        action_family="manage",
        execution_mode="server",
        stage_support=["move", "inspect", "prepare", "execute"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="medium",
        manual_links=_links(("VI Portal Runtime", "/wiki/vi-portal-runtime"), ("Platform Foundations", "/wiki/platform-foundations")),
    ),
    _capability(
        "verse.chat.manage",
        title="Manage Verse Thread Workflow",
        summary="Create threads, send messages, invite specialists, and synthesize conversations.",
        subsystem="verse",
        surface_id="verse-ai",
        surface_path="/verse-ai",
        action_family="conversation",
        execution_mode="server",
        stage_support=["inspect", "execute"],
        supports={"verse": True, "cli": False, "ui": True},
        risk_level="low",
        manual_links=_links(("Verse Agents", "/wiki/verse-agents-reference"), ("Platform Foundations", "/wiki/platform-foundations")),
    ),
    _capability(
        "verse.datasets.manage",
        title="Manage Verse Datasets",
        summary="Create, upload, inspect, and refresh datasets used by Ananse and Verse analytics.",
        subsystem="verse",
        surface_id="ananse-workbench",
        surface_path="/ananse-workbench",
        action_family="dataset",
        execution_mode="server",
        stage_support=["move", "inspect", "prepare", "execute"],
        supports={"verse": True, "cli": False, "ui": True},
        risk_level="medium",
        manual_links=_links(("Verse Agents", "/wiki/verse-agents-reference"), ("Platform Foundations", "/wiki/platform-foundations")),
    ),
    _capability(
        "ananse.analysis.open",
        title="Open Deeper Analysis",
        summary="Open or refresh richer Ananse analysis views for a saved dataset.",
        subsystem="ananse",
        surface_id="ananse-workbench",
        surface_path="/ananse-workbench",
        action_family="analyze",
        execution_mode="page",
        stage_support=["move", "prepare", "execute"],
        supports={"verse": True, "cli": False, "ui": True},
        risk_level="low",
        artifact_kind="ananse-analysis",
        manual_links=_links(("Verse Agents", "/wiki/verse-agents-reference"), ("Platform Foundations", "/wiki/platform-foundations")),
    ),
    _capability(
        "verse.mind-share.apply",
        title="Apply Mind-Share Update",
        summary="Preview or apply curated Verse operational learning and shared memory writes.",
        subsystem="verse",
        surface_id="verse-ai",
        surface_path="/verse-ai",
        action_family="memory",
        execution_mode="server",
        stage_support=["inspect", "prepare", "execute"],
        supports={"verse": True, "cli": False, "ui": True},
        risk_level="medium",
        manual_links=_links(("Verse Agents", "/wiki/verse-agents-reference"), ("Platform Foundations", "/wiki/platform-foundations")),
    ),
    _capability(
        "docs.wiki.open",
        title="Open Platform Manual",
        summary="Open the right public manual or workspace guide for the requested feature.",
        subsystem="docs",
        surface_id="wiki",
        surface_path="/wiki",
        action_family="inspect",
        execution_mode="page",
        stage_support=["move", "inspect"],
        supports={"verse": True, "cli": True, "ui": True},
        risk_level="low",
        manual_links=_links(("Platform Foundations", "/wiki/platform-foundations"), ("Verse Agents", "/wiki/verse-agents-reference")),
    ),
]


_ARTIFACT_CAPABILITY_IDS = {
    "ananse-analysis": "ananse.analysis.open",
    "service-builder-lapis": "service.builder.generate",
    "vi-script": "vi.script.draft",
    "vdb-query": "vdb.query.run",
}

_SERVICE_MANAGER_ACTION_CAPABILITY_IDS = {
    "start": "service.manager.start",
    "stop": "service.manager.stop",
    "delete": "service.manager.delete",
}


def _copy_capability(record: dict[str, Any]) -> dict[str, Any]:
    return {
        **record,
        "stageSupport": list(record.get("stageSupport") or []),
        "supports": dict(record.get("supports") or {}),
        "permissions": [str(item).strip() for item in list(record.get("permissions") or []) if str(item).strip()],
        "manualLinks": [
            {"title": str(item.get("title") or "").strip(), "href": str(item.get("href") or "").strip()}
            for item in list(record.get("manualLinks") or [])
            if isinstance(item, dict) and str(item.get("title") or "").strip() and str(item.get("href") or "").strip()
        ],
    }


def list_platform_capabilities(
    *,
    client: str = "",
    surface_id: str = "",
    executable_only: bool = False,
) -> list[dict[str, Any]]:
    normalized_client = str(client or "").strip().lower()
    normalized_surface = str(surface_id or "").strip().lower()
    items: list[dict[str, Any]] = []
    for raw in _PLATFORM_CAPABILITIES:
        record = _copy_capability(raw)
        if normalized_client and not bool((record.get("supports") or {}).get(normalized_client)):
            continue
        if normalized_surface and str(record.get("surfaceId") or "").strip().lower() != normalized_surface:
            continue
        if executable_only and str(record.get("executionMode") or "").strip().lower() not in {"page", "server"}:
            continue
        items.append(record)
    return items


def get_platform_capability(capability_id: str) -> dict[str, Any] | None:
    normalized = str(capability_id or "").strip()
    if not normalized:
        return None
    for record in _PLATFORM_CAPABILITIES:
        if str(record.get("capabilityId") or "").strip() == normalized:
            return _copy_capability(record)
    return None


def capability_id_for_artifact(kind: str, action: str = "") -> str:
    normalized_kind = str(kind or "").strip()
    if normalized_kind == "service-manager-action":
        return _SERVICE_MANAGER_ACTION_CAPABILITY_IDS.get(str(action or "").strip().lower(), "")
    return _ARTIFACT_CAPABILITY_IDS.get(normalized_kind, "")
